// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBghl6icUG7L0MXCuYW0vtUJqK_Eaw05tM',
    appId: '1:251484628717:android:c9b6d6fd77d9f71f8e4ee4',
    messagingSenderId: '251484628717',
    projectId: 'example-376c0',
    databaseURL: 'https://example-376c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'example-376c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF4hMkhuXFN---0VQyfBPQddF7Q905Ixw',
    appId: '1:251484628717:ios:70e245f74f335f398e4ee4',
    messagingSenderId: '251484628717',
    projectId: 'example-376c0',
    databaseURL: 'https://example-376c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'example-376c0.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );
}
