name: travel_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animate_do: ^3.0.2
  shape_of_view_null_safe: ^2.0.0
  google_fonts: ^4.0.1
  water_drop_nav_bar: ^2.2.0+5
  firebase_core: ^2.32.0
  firebase_analytics: ^10.4.3
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.7
  firebase_crashlytics: ^3.3.3
  firebase_ui_firestore: ^1.5.5
  firebase_auth: ^4.10.0
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.1.0
  firebase_app_check: ^0.2.1+6
  firebase_remote_config: ^4.3.8
  connectivity_plus: ^4.0.2
  shared_preferences: ^2.2.1
  get: ^4.6.6
  lottie: ^2.7.0
  image_picker: ^1.0.4
  sign_in_button: ^3.2.0
  google_sign_in: ^6.1.6
  uuid: ^3.0.4
  flutter_launcher_icons: ^0.9.2
  table_calendar: ^3.0.0
  file_picker: ^8.0.6
  http: ^1.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/T_M_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - assets/data/

  fonts:
     - family: clover
       fonts:
         - asset: assets/font/EF_jejudoldam(TTF).ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
